# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11-uxEGE7HWW8h1I7JlpJzmkbGNyJtWtD

# SMART MEDICINAL PLANT IDENTIFICATION SYSTEM (SMPIS)

# libraries
"""

# necessary dependencies
import numpy as np
import pandas as pd
import os
import random

# data processing
from PIL import Image, ImageOps
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.applications.vgg19 import preprocess_input

# model handling
from tensorflow.keras.applications import VGG19
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
from sklearn.model_selection import train_test_split

# performance measurement
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

"""# getting the data"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("eyadalhusseini/medicinal-plant-identification-dataset")

print("Path to dataset files:", path)

os.listdir(path)

path = os.path.join(path, 'Medicinal Plant Identification Dataset')
print(os.listdir(path))

path = os.path.join(path, 'Augmented-Images')
print(os.listdir(path))

imgexts = {".jpg", ".jpeg", ".png"}

total = 0
counts = {}

for folder in os.listdir(path):
    folderpath = os.path.join(path, folder)

    if not os.path.isdir(folderpath):
        continue

    images = [
        f for f in os.listdir(folderpath)
        if os.path.splitext(f)[1].lower() in imgexts
    ]

    count = len(images)
    counts[folder] = count
    total += count

    print(f"{folder}: {count} images")

print("\nTotal images:", total)

"""
getting the data from the folders...
...as paths and label
"""
data = []
max = 490

for folder in os.listdir(path):
    # getting the folder path form path
    folderpath = os.path.join(path, folder)
    if not os.path.isdir(folderpath):
        continue
    # getting images and checking lower ? image exits
    images = [
        f for f in os.listdir(folderpath)
        if os.path.splitext(f)[1].lower() in imgexts
    ]

    # ensuring class balance
    # randomize order
    random.shuffle(images)
    # cap at max per folder
    images = images[:max]

    print(folder, "has", len(images), "images (capped)")

    for imgname in images:
      # getting the image path + folder path
        imgpath = os.path.join(folderpath, imgname)
        data.append((imgpath, folder))

print("Total loaded:", len(data))

"""### truning it into a dataframe"""

df = pd.DataFrame(data,columns=["paths", "label"])

df.sample(5)

"""
df[x]['label'] =  Mint Leaf --> df[x]['label'] =  Mint Leaf  = 4
"""
le = LabelEncoder()
df['labelencoded'] = le.fit_transform(df['label'])

df.sample(5)

"""# pre-processing the data

note: this cell takes a lot of time
"""

"""
We go through the entire dataframe:
1- Making sure the images are RGB.
2- We use ImageOps to make sure all images are the same size.
3- We convert the images into a NumPy array.
4- Apply VGG19 preprocessing to x.
"""
target_size = (224, 224)

x = []
y = []

for row in df.itertuples(index=False):
    img = Image.open(row.paths).convert("RGB")
    img = ImageOps.pad(img, target_size)

    x.append(np.asarray(img, dtype=np.float32))
    y.append(row.labelencoded)

x = np.asarray(x, dtype=np.float32)
y = np.asarray(y)

x = preprocess_input(x)

print(x.shape,y.shape)
print(x.dtype)

"""### splting the data"""

xtrain, xtest,ytrain,ytest = train_test_split(
    x,y,
    test_size=0.2,
    stratify=y, # ensuring class balance
    random_state=42
)

print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

"""# model time

### initializing the backbone
"""

basemodel = VGG19(
    # weights = imagenet
    include_top = False,
    input_shape = (224,224,3)
)

"""
freezing the layers of the model(VGG19) itself
"""
for layer in basemodel.layers:
  layer.trainable = False

"""### making the classification head"""

x = basemodel.output # the yield of the output layer
x = Flatten()(x) # flatten so we can train a layer on our data
x = Dense(256,activation='relu')(x) # said layer
output = Dense(6,activation='softmax')(x) # the class classifier

"""### compiling the final model"""

# attaching the classification head
model = Model(inputs = basemodel.input,outputs=output)

model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics = ['accuracy']
)

"""# the Magnum opus"""

history = model.fit(
    xtrain,ytrain,
    validation_data = (xtest,ytest),
    batch_size=32,
    epochs=30
)

"""# performance measurement"""

ypred_probs = model.predict(xtest)

ypred = np.argmax(ypred_probs, axis=1)

acc = accuracy_score(ytest, ypred)
print("Validation accuracy:", acc)

print(classification_report(
    ytest,
    ypred,
    target_names=le.classes_
))

"""# deployment"""

model.save('leaf_model.keras')